apiVersion: v1
kind: Pod                               # Kind of resource we are creating
metadata:
  name: sa-frontend2                     # Name of the resource
  #labels:
  #  app: sa-frontend 
spec:
  containers:
    - image: mihailrc/sa-frontend      # Docker image to use
      name: sa-frontend                # name of the container within the pod
      ports:
        - containerPort: 80            # Port to listen to - informational
